### ISSUE TITLE
Verify Tagar's Spark optimisations

### ISSUE THREAD

**Issue by dereksdata** [dereksdata/hadoop-kickstart#1]
## to address Spark netty spike in network activity :

net.ipv4.ip_local_port_range = 2000 65535
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 2048
net.ipv4.tcp_synack_retries = 3
net.ipv4.tcp_fin_timeout = 20
net.ipv4.tcp_max_syn_backlog = 8096
net.core.netdev_max_backlog = 16000
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.ipv4.tcp_rmem = 4096 87380 134217728
net.ipv4.tcp_wmem = 4096 65536 134217728
net.core.rmem_default = 262144
net.core.wmem_default = 262144

**Comment by Tagar** [comment]
See https://github.com/dereksdata/hadoop-kickstart/commit/8fbdda2a192758bc3f8f849eb8fca8aed8e89ad6#commitcomment-18745593 for some details.
